return {
  --
  -- "MykolaVaskevych/qmk.nvim",
  -- branch = "fix/unicode-character-support",
  "codethread/qmk.nvim",
  ft = { "dts", "c" }, -- Load for devicetree and C files

  opts = {
    name = "lily58", -- Using your keyboard name
    variant = "zmk", -- Since you're using .keymap files, this is ZMK
    layout = {
      -- Lily58 layout with wider split for visual separation
      "x x x x x x _ _ _ _ x x x x x x",
      "x x x x x x _ _ _ _ x x x x x x",
      "x x x x x x _ _ _ _ x x x x x x",
      "x x x x x x x _ _ x x x x x x x",
      "_ _ _ x x x x _ _ x x x x _ _ _",
    },
    auto_format_pattern = "*.keymap", -- Auto format .keymap files on save
    comment_preview = {
      position = "top", -- Show preview at top of keymap
      keymap_overrides = {
        -- Shorten long key names for cleaner preview
        ["&kp LEFT_SHIFT"] = "LSHFT",
        ["&kp RIGHT_SHIFT"] = "RSHFT",
        ["&kp LEFT_CONTROL"] = "LCTRL",
        ["&kp RIGHT_CONTROL"] = "RCTRL",
        ["&kp LEFT_ALT"] = "LALT",
        ["&kp RIGHT_ALT"] = "RALT",
        ["&kp LEFT_WIN"] = "LGUI",
        ["&kp RIGHT_WIN"] = "RGUI",
        ["&kp LEFT_GUI"] = "LGUI",
        ["&kp RIGHT_GUI"] = "RGUI",
        ["&kp BACKSPACE"] = "BSPC",
        ["&kp SEMICOLON"] = ";",
        ["&kp SINGLE_QUOTE"] = "'",
        ["&kp PRINTSCREEN"] = "PSCR",
        ["&kp PAGE_DOWN"] = "PGDN",
        ["&kp INSERT"] = "INS",
        ["&kp ESCAPE"] = "ESC",
        ["&kp SPACE"] = "SPC",
        ["&kp ENTER"] = "ENT",
        ["&kp DELETE"] = "DEL",
        ["&kp TAB"] = "TAB",
        ["&gresc"] = "ESC",
        ["&trans"] = "---",
        ["&none"] = "___",
        -- Layer switches with labels
        ["&mo 1"] = "Mac",
        ["&mo 2"] = "Fn⬆",
        ["&mo 3"] = "Sym",
        ["&mo 4"] = "Game",
        ["&mo 5"] = "BT",
        ["&mo 6"] = "Media",
        ["&lt 3 ESC"] = "Sym⎋",
        -- Mod-tap combinations with symbols
        ["&mt LEFT_WIN A"] = "⌘A",
        ["&mt LEFT_ALT S"] = "⌥S",
        ["&mt LEFT_SHIFT D"] = "⇧D",
        ["&mt LCTRL F"] = "⌃F",
        ["&mt RCTRL J"] = "⌃J",
        ["&mt RIGHT_SHIFT K"] = "⇧K",
        ["&mt RIGHT_ALT L"] = "⌥L",
        ["&mt LEFT_WIN SEMICOLON"] = "⌘;",
        ["&mt RIGHT_WIN SEMICOLON"] = "⌘;",
        ["&mt LEFT_GUI F"] = "⌘F",
        ["&mt RIGHT_GUI J"] = "⌘J",
        ["&mt LEFT_CONTROL S"] = "⌃S",
        ["&mt LEFT_CONTROL L"] = "⌃L",
        ["&mt LEFT_ALT SEMICOLON"] = "⌥;",
        -- F-key mod-taps
        ["&mt LEFT_WIN F6"] = "⌘F6",
        ["&mt LEFT_ALT F7"] = "⌥F7",
        ["&mt LEFT_SHIFT F8"] = "⇧F8",
        ["&mt LCTRL F9"] = "⌃F9",
        -- Symbol mod-taps
        ["&mt LEFT_GUI LESS_THAN"] = "⌘<",
        ["&mt LEFT_ALT GREATER_THAN"] = "⌥>",
        ["&mt LEFT_SHIFT LBRC"] = "⇧{",
        ["&mt LCTRL RBRC"] = "⌃}",
        -- Special keys
        ["&kp LC(BACKSPACE)"] = "⌃⌫",
        ["&kp LA(BACKSPACE)"] = "⌥⌫",
        ["&kp LS(LPAR)"] = "(",
        ["&kp LS(RPAR)"] = ")",
        ["&kp LBKT"] = "[",
        ["&kp RBKT"] = "]",
        ["&kp LBRC"] = "{",
        ["&kp RBRC"] = "}",
        ["&kp UNDERSCORE"] = "_",
        ["&kp LESS_THAN"] = "<",
        ["&kp GREATER_THAN"] = ">",
        ["&kp EXCLAMATION"] = "!",
        ["&kp PERCENT"] = "%",
        ["&kp AMPERSAND"] = "&",
        ["&kp ASTERISK"] = "*",
        ["&kp HASH"] = "#",
        ["&kp CARET"] = "^",
        ["&kp DLLR"] = "$",
        ["&kp SLASH"] = "/",
        ["&kp BACKSLASH"] = "\\",
        ["&kp TILDE"] = "~",
        ["&kp PIPE"] = "|",
        ["&kp MINUS"] = "-",
        ["&kp PLUS"] = "+",
        ["&kp EQUAL"] = "=",
        ["&kp COMMA"] = ",",
        ["&kp DOT"] = ".",
        ["&kp FSLH"] = "/",
        ["&kp SQT"] = "'",
        ["&kp LEFT"] = "←",
        ["&kp RIGHT"] = "→",
        ["&kp UP"] = "↑",
        ["&kp DOWN"] = "↓",
        ["&kp HOME"] = "Home",
        ["&kp END"] = "End",
        ["&kp PG_UP"] = "PgUp",
        ["&kp C_VOL_DN"] = "Vol-",
        ["&kp C_VOL_UP"] = "Vol+",
        ["&kp C_PP"] = "⏯",
        ["&kp C_PREV"] = "⏮",
        ["&kp C_NEXT"] = "⏭",
        -- Bluetooth
        ["&bt BT_SEL 0"] = "BT0",
        ["&bt BT_SEL 1"] = "BT1",
        ["&bt BT_SEL 2"] = "BT2",
        ["&bt BT_SEL 3"] = "BT3",
        ["&bt BT_SEL 4"] = "BT4",
        ["&bt BT_CLR"] = "CLR",
        ["&bt BT_NXT"] = "BT→",
        ["&bt BT_PRV"] = "BT←",
      },
    },
  },
  dependencies = {
    "nvim-treesitter/nvim-treesitter", -- Required for syntax parsing
  },
}
